### ISSUE TITLE
error installing in a docker container

### ISSUE THREAD

**Issue by scottdraves** [lmcinnes/umap#154]
reverting to 0.3.2 fixes this problem. not sure what the locale settings are in there but probably best to just avoid any tricky characters in the readme (Großberger), or specify the encoding where the file is read https://github.com/lmcinnes/umap/blob/bc354b8c6d9b2179408f016ba701399ebd89b843/setup.py#L5

```
Collecting umap-learn==0.3.5 (from -r requirements.txt (line 76))
  Downloading https://files.pythonhosted.org/packages/aa/f9/338a9fe0ec36be32564ad5c57897c36f16c8b34ba79a16de5e35f394ed98/umap-learn-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9jc8s59j/umap-learn/setup.py", line 11, in <module>
        'long_description' : readme(),
      File "/tmp/pip-install-9jc8s59j/umap-learn/setup.py", line 5, in readme
        return readme_file.read()
      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9848: ordinal not in range(128)
```

**Comment by lmcinnes** [comment]
Fair enough -- I hadn't foreseen any issues and figured I should credit people as correctly as I could. I'll try to fix it and roll out a new release soon.

**Comment by sleighsoft** [comment]
Seems like @lmcinnes fixed this already. Closing.
