### ISSUE TITLE
mapper.transform(test_data)

### ISSUE THREAD

**Issue by zpingfeng** [lmcinnes/umap#171]
When I tested the  "Training with Labels and Embedding Unlabelled Test Data (Metric Learning with UMAP)" part, with 'python-mnist/data', it is all fine until I 'mapper.transform(test_data)'. Please see the details below. What is the problem? Any idea?

%%time
mapper = umap.UMAP(n_neighbors=10).fit(train_data, np.array(train_labels))

%%time
test_embedding = mapper.transform(test_data)
Traceback (most recent call last):

  File "<timed exec>", line 1, in <module>

  File "/Applications/anaconda3/lib/python3.6/site-packages/umap/umap_.py", line 1627, in transform
    X,

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 494, in stage_parfor_pass
    parfor_pass.run()

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/parfor.py", line 198, in run
    self._convert_prange(self.func_ir.blocks)
 File "/Applications/anaconda3/lib/python3.6/site-packages/numba/parfor.py", line 346, in _convert_prange
    self._convert_prange(parfor_blocks)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/parfor.py", line 264, in _convert_prange
    call_table, _ = get_call_table(blocks)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/ir_utils.py", line 874, in get_call_table
    topo_order = find_topo_order(blocks)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/ir_utils.py", line 838, in find_topo_order
    cfg = compute_cfg_from_blocks(blocks)

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/analysis.py", line 211, in compute_cfg_from_blocks
    term = b.terminator

  File "/Applications/anaconda3/lib/python3.6/site-packages/numba/ir.py", line 780, in terminator
    return self.body[-1]

IndexError: Failed at nopython (convert to parfors)
list index out of range

**Comment by zpingfeng** [comment]
Thanks for the quick answering! I updated everything, but more troubles are coming. Something working perfectly yesterday is not working today :-(.  see details below:

from sklearn.datasets import load_iris, load_digits
Traceback (most recent call last):

  File "<ipython-input-35-7d4fee28c13e>", line 1, in <module>
    from sklearn.datasets import load_iris, load_digits

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/datasets/__init__.py", line 23, in <module>
    from .twenty_newsgroups import fetch_20newsgroups

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/datasets/twenty_newsgroups.py", line 44, in <module>
    from ..feature_extraction.text import CountVectorizer

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/__init__.py", line 10, in <module>
    from . import text

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 30, in <module>
    from ..preprocessing import normalize

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/testing.py", line 385, in <module>
    assert_allclose = np.testing.assert_allclose

AttributeError: module 'numpy' has no attribute 'testing'


import umap

reducer = umap.UMAP()
Traceback (most recent call last):

  File "<ipython-input-37-670e0ad4d6f6>", line 1, in <module>
    reducer = umap.UMAP()

AttributeError: module 'umap' has no attribute 'UMAP'

**Comment by lmcinnes** [comment]
I think you need to remove anything in site-packages named umap and then
re-install umap-learn.

**Comment by zpingfeng** [comment]
I did, but :-(

1) pip uninstall umap
Uninstalling umap-0.1.1:
  Would remove:
    /Applications/anaconda3/lib/python3.7/site-packages/umap-0.1.1.dist-info/*
    /Applications/anaconda3/lib/python3.7/site-packages/umap/*
  Would not remove (might be manually added):
    /Applications/anaconda3/lib/python3.7/site-packages/umap/distances.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/nndescent.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/rp_tree.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/sparse.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/spectral.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/umap_.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/utils.py
    /Applications/anaconda3/lib/python3.7/site-packages/umap/validation.py
Proceed (y/n)? y
  Successfully uninstalled umap-0.1.1

2)  pip install umap-learn
Requirement already satisfied: umap-learn in /Applications/anaconda3/lib/python3.7/site-packages (0.3.7)
Requirement already satisfied: scipy>=0.19 in /Applications/anaconda3/lib/python3.7/site-packages (from umap-learn) (1.1.0)
Requirement already satisfied: numba>=0.37 in /Applications/anaconda3/lib/python3.7/site-packages (from umap-learn) (0.41.0)
Requirement already satisfied: scikit-learn>=0.16 in /Applications/anaconda3/lib/python3.7/site-packages (from umap-learn) (0.20.1)
Requirement already satisfied: numpy>=1.13 in /Applications/anaconda3/lib/python3.7/site-packages (from umap-learn) (1.15.4)
Requirement already satisfied: llvmlite>=0.26.0dev0 in /Applications/anaconda3/lib/python3.7/site-packages (from numba>=0.37->umap-learn) (0.26.0)

then 3):
import umap
from sklearn.datasets import load_digits
Traceback (most recent call last):

  File "<ipython-input-59-14f8b2589bed>", line 1, in <module>
    from sklearn.datasets import load_digits

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/datasets/__init__.py", line 23, in <module>
    from .twenty_newsgroups import fetch_20newsgroups

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/datasets/twenty_newsgroups.py", line 44, in <module>
    from ..feature_extraction.text import CountVectorizer

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/__init__.py", line 10, in <module>
    from . import text

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py", line 30, in <module>
    from ..preprocessing import normalize

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse

  File "/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/testing.py", line 385, in <module>
    assert_allclose = np.testing.assert_allclose

AttributeError: module 'numpy' has no attribute 'testing'




reducer = umap.UMAP()
Traceback (most recent call last):

  File "<ipython-input-60-670e0ad4d6f6>", line 1, in <module>
    reducer = umap.UMAP()

AttributeError: module 'umap' has no attribute 'UMAP'
