### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by sauln** [lmcinnes/umap#19]
I was had some trouble getting umap installed on my system. I think the problem was with getting numba to work properly without using Anaconda. 

```
Traceback (most recent call last):
  File "visualize.py", line 2, in <module>
    import umap
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/umap/umap_.py", line 7, in <module>
    import numba
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/__init__.py", line 12, in <module>
    from .special import typeof, prange
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/typing/__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/typing/context.py", line 10, in <module>
    from numba.typeconv import Conversion, rules
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/typeconv/rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/home/sauln/research/graphs/venv/lib/python3.6/site-packages/numba/typeconv/typeconv.py", line 3, in <module>
    from . import _typeconv, castgraph, Conversion
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
````

I was able to get everything to work without using Conda by installing the python dev:
``` 
sudo apt-get install libpython3.6-dev
```

Though my issue is already solved, other people might run into the same problems. It might be helpful to incorporate this information into the docs somewhere, or just close the issue and direct people here if it comes up again.

**Comment by lmcinnes** [comment]
Thanks for the report! I'll leave this open here for a while so others can find it if they encounter something similar.

**Comment by sleighsoft** [comment]
For future users that might end up here:
```
conda create -n umap python=3.6
conda activate umap
pip install umap-learn
```
