### ISSUE TITLE
Build failures :: numba-integration-testing

### ISSUE THREAD

**Issue by esc** [lmcinnes/umap#244]
We are currently experiencing build failures with the numba-integration-testing repo. The error is:

```
======================================================================
ERROR: Failure: ImportError (cannot import name 'if_matplotlib' from 'sklearn.utils.testing' (/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/sklearn/utils/testing.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/repo/umap/umap/tests/test_umap.py", line 12, in <module>
    from sklearn.utils.testing import (
ImportError: cannot import name 'if_matplotlib' from 'sklearn.utils.testing' (/home/circleci/repo/miniconda3/envs/umap/lib/python3.7/site-packages/sklearn/utils/testing.py)
```

Here is an example build:

https://circleci.com/gh/numba/numba-integration-testing/250

**Comment by lmcinnes** [comment]
Thanks for the report -- it seems that sklearn updated some things, and ``if_matplotlib`` is no longer supported. Fortunately that's easy enough to fix in this case. Are you builidng directly from the repository, or do you need a release to be made?

**Comment by esc** [comment]
If it is not too much hassle, a new release would be ideal.

On 27 May 2019 15:59:14 CEST, Leland McInnes <notifications@github.com> wrote:
>Thanks for the report -- it seems that sklearn updated some things, and
>``if_matplotlib`` is no longer supported. Fortunately that's easy
>enough to fix in this case. Are you builidng directly from the
>repository, or do you need a release to be made?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lmcinnes/umap/issues/244#issuecomment-496222227

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lmcinnes** [comment]
I'll see what I can do -- it seems to have been already fixed in master as far as I can tell.

**Comment by lmcinnes** [comment]
0.3.9 should be up shortly and hopefully that will cover your needs.

**Comment by esc** [comment]
looks good, this mornings integrations tests for umap passed once again! Thank you very much!

**Comment by lmcinnes** [comment]
Glad I could help -- Numba is amazing, and you all do amazing work on it.

**Comment by esc** [comment]
Awwww, thanks! 

On 28 May 2019 15:38:29 CEST, Leland McInnes <notifications@github.com> wrote:
>Glad I could help -- Numba is amazing, and you all do amazing work on
>it.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/lmcinnes/umap/issues/244#issuecomment-496520087

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
