### ISSUE TITLE
import umap fails due to inability to load share object file llvmlite when importing numba 

### ISSUE THREAD

**Issue by LaithYZumot** [lmcinnes/umap#280]
Python 3.6.9 (default, Jul  3 2019, 15:36:16) 
[GCC 5.4.0 20160609] on linux
>>> import umap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/usr/local/lib/python3.6/dist-packages/umap/umap_.py", line 24, in <module>
    import numba
  File "/usr/local/lib/python3.6/dist-packages/numba-0.45.1-py3.6-linux-x86_64.egg/numba/__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File "/usr/local/lib/python3.6/dist-packages/numba-0.45.1-py3.6-linux-x86_64.egg/numba/config.py", line 18, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.29.0-py3.6.egg/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.29.0-py3.6.egg/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.29.0-py3.6.egg/llvmlite/binding/ffi.py", line 154, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

**Comment by LaithYZumot** [comment]
Issue is due to Numba package itself not related to Umap.
