### ISSUE TITLE
loading umap with joblib error ("RuntimeError: incompatible bytecode version")

### ISSUE THREAD

**Issue by shashi-netra** [lmcinnes/umap#312]
I am saving a UMAP object into a `joblib` file on an Ubuntu box and then loading the Umap object on my mbp. I get this error:

```
xxx@xxx-MBP jobs % python3                   
Python 3.7.3 (default, May 29 2019, 13:53:17) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import joblib
>>> umap = joblib.load("clf_umap-1000.job")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py", line 1433, in load_reduce
    stack[-1] = func(*args)
  File "/usr/local/lib/python3.7/site-packages/numba/serialize.py", line 31, in _rebuild_reduction
    return cls._rebuild(*args)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 715, in _rebuild
    py_func = serialize._rebuild_function(*func_reduced)
  File "/usr/local/lib/python3.7/site-packages/numba/serialize.py", line 99, in _rebuild_function
    code = _rebuild_code(*code_reduced)
  File "/usr/local/lib/python3.7/site-packages/numba/serialize.py", line 118, in _rebuild_code
    raise RuntimeError("incompatible bytecode version")
RuntimeError: incompatible bytecode version
```
I can run the same Umap object fine on the Ubuntu box. I have verified the `joblib`, `numba` and `umap` libraries are both the same version on both. what could I be doing wrong? I suspect this is some dependency incompatibility.

**Comment by VolodyaCO** [comment]
I have the same issue!
