### ISSUE TITLE
Problem with import umap.plot

### ISSUE THREAD

**Issue by AnastasiiaKabeshova** [lmcinnes/umap#365]
After installing UMAP still 

> ModuleNotFoundError: No module named 'umap.plot'

**Comment by gokceneraslan** [comment]
Maybe missing package? Documentation says:

The umap.plot package requires extra plotting libraries to be installed.
    You can install these via pip using
    
    pip install umap-learn[plot]
    
    or via conda using
    
    conda install seaborn datashader bokeh holoviews

**Comment by alexsosn** [comment]
I have the same problem. All requirements for plotting and umap itself are installed.
`pip install umap-learn[plot]` gives:

```
Collecting umap-learn[plot]
  umap-learn 0.3.10 does not provide the extra 'plot'
... [the list of satisfied requirements follows]...
Installing collected packages: umap-learn
Successfully installed umap-learn-0.3.10
```

Please note the second line.

**Comment by qoffee** [comment]
Plus!!! I have the same problem and I was very upset when a few days ago, I could not find it!

**Comment by lmcinnes** [comment]
You need to install the pre-release version at this time. You can do that via:

```
pip install --pre umap-learn
```

You can check that you have the right version by ensuring that you have umap-learn 0.4.0rc1.

**Comment by AnastasiiaKabeshova** [comment]
Thank you! It did work for me!

**Comment by thommiano** [comment]
Is plot still only available on `0.4dev branch`? Even with all the packages installed via `pip install umap-learn[plot]` I'm still getting the error:

```bash
/Users/tmiano/.pyenv/versions/3.8.0/lib/python3.8/site-packages/umap/plot.py:20: UserWarning: The umap.plot package requires extra plotting libraries to be installed.
    You can install these via pip using

    pip install umap-learn[plot]

    or via conda using

     conda install pandas matplotlib datashader bokeh holoviews colorcet scikit-image

  warn(
Traceback (most recent call last):
  File "bookworm/embeddings/visualize.py", line 3, in <module>
    import umap.plot
  File "/Users/tmiano/.pyenv/versions/3.8.0/lib/python3.8/site-packages/umap/plot.py", line 31, in <module>
    raise ImportError(
ImportError: umap.plot requires pandas matplotlib datashader bokeh holoviews scikit-image and colorcet to be installed
```

I've also manually checked that each of these packages are available.

**Comment by lmcinnes** [comment]
It should work, but it seems there is something that doesn't import. Can you try the following imports in your environment and let me know which import fails?

```python
    import pandas as pd
    import datashader as ds
    import datashader.transfer_functions as tf
    import datashader.bundling as bd
    import matplotlib.pyplot as plt
    import colorcet
    import matplotlib.colors
    import matplotlib.cm

    import bokeh.plotting as bpl
    import bokeh.transform as btr
    import holoviews as hv
    import holoviews.operation.datashader as hd
```

**Comment by gsalfourn** [comment]
@lmcinnes 

I tried the following imports in Python 3.9

```
import pandas as pd
import datashader as ds
import datashader.transfer_functions as tf
import datashader.bundling as bd
import matplotlib.pyplot as plt
import colorcet
import matplotlib.colors
import matplotlib.cm

import bokeh.plotting as bpl
import bokeh.transform as btr
import holoviews as hv
import holoviews.operation.datashader as hd
```

but got some error shown below

```AttributeError: module 'time' has no attribute 'clock'

Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\IPython\utils\timing.py", line 27, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\content analysis\bertopic\_importing umap-plot.py", line 12, in <module>
    import holoviews as hv
  File "C:\Python\Python39\lib\site-packages\holoviews\__init__.py", line 41, in <module>
    import IPython                 # noqa (API import)
  File "C:\Python\Python39\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Python\Python39\lib\site-packages\IPython\terminal\embed.py", line 19, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "C:\Python\Python39\lib\site-packages\IPython\terminal\ipapp.py", line 30, in <module>
    from IPython.core.magics import ScriptMagics
  File "C:\Python\Python39\lib\site-packages\IPython\core\magics\__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "C:\Python\Python39\lib\site-packages\IPython\core\magics\execution.py", line 46, in <module>
    from IPython.utils.timing import clock, clock2
  File "C:\Python\Python39\lib\site-packages\IPython\utils\timing.py", line 64, in <module>
    clocku = clocks = clock = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by haghob** [comment]
It didn’t work for me, I installed the necessary packages but still the same error!! 
"ModuleNotFoundError: No module named 'umap.plot'"
