### ISSUE TITLE
fit/transform/inverse_transform broken for custom distance metrics

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [lmcinnes/umap#366]
hey @lmcinnes, thanks for maintaining such an awesome package.  Looks like 0.4 is getting close to release -- super exciting!  

I'm running into a couple issues with using custom distance functions (using the repo, master branch, most recent commit lmcinnes/umap@1a3892610643ca0ba72a0c559488f47e43bbd7cf):
1. if a callable `output_metric` is passed, [`simplicial_set_embedding` calls `optimize_layout_generic`](https://github.com/lmcinnes/umap/blob/1a3892610643ca0ba72a0c559488f47e43bbd7cf/umap/umap_.py#L1103), which fails [here](https://github.com/lmcinnes/umap/blob/1a3892610643ca0ba72a0c559488f47e43bbd7cf/umap/layouts.py#L341) with a numba `TypingError`, because it expects to be using the gradient-returning version of a built-in named metric, which would return a tuple.  This would also affect the `transform` method [here](https://github.com/lmcinnes/umap/blob/1a3892610643ca0ba72a0c559488f47e43bbd7cf/umap/umap_.py#L2074) for the same reason.
2. Similarly, if a callable `metric` is passed, the `inverse_transform` method won't work because `optimize_layout_inverse` fails [here](https://github.com/lmcinnes/umap/blob/1a3892610643ca0ba72a0c559488f47e43bbd7cf/umap/layouts.py#L505) for the same reason.

I'm planning to try to fix this on my own fork anyway, so I'd be happy to submit a PR when I'm done if you're interested! There are a couple different ways I think it could be addressed, depending on what you'd prefer, but each is a bit tricky and has its downsides.

Oh, also, it looks like the fixes I submitted in #330 were overwritten by a subsequent pull request.  If you want, I could re-add those changes.

Thanks again!

**Comment by paxtonfitzpatrick** [comment]
Ah, forgot to add this:
<details>
<summary>Code for reproducing 1:</summary>

```
import numba
import numpy as np
from umap import UMAP


@numba.njit(fastmath=True)
def euclidean_custom(x, y):
    # equivalent to existing euclidean distance function
    result = 0.0
    for i in range(x.shape[0]):
        result += (x[i] - y[i]) ** 2
    return np.sqrt(result)


np.random.seed(0)
to_reduce = np.random.uniform(0, 1, (2000, 25))
reducer = UMAP(random_state=0, output_metric=euclidean_custom).fit(to_reduce)
```
</details>
<details>
<summary>Traceback:</summary>

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-47-62bd2706cb2a> in <module>
     12
---> 13 reducer = UMAP(random_state=0, output_metric=euclidean_custom).fit(to_reduce)

~/Documents/Dartmouth/CDL/umap/umap/umap_.py in fit(self, X, y)
   1865             self.output_metric in ("euclidean", "l2"),
   1866             self.random_state is None,
-> 1867             self.verbose,
   1868         )[inverse]
   1869 

~/Documents/Dartmouth/CDL/umap/umap/umap_.py in simplicial_set_embedding(data, graph, n_components, initial_alpha, a, b, gamma, negative_sample_rate, n_epochs, init, random_state, metric, metric_kwds, output_metric, output_metric_kwds, euclidean_output, parallel, verbose)
   1118             output_metric,
   1119             tuple(output_metric_kwds.values()),
-> 1120             verbose=verbose,
   1121         )
   1122 

~/opt/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

~/opt/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

~/opt/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
failed to unpack float64

File "umap/layouts.py", line 342:
def optimize_layout_generic(
    <source elided>
                dist_output, grad_dist_output = output_metric(
                    current, other, *output_metric_kwds
                    ^

[1] During: typing of exhaust iter at /Users/paxtonfitzpatrick/Documents/Dartmouth/CDL/umap/umap/layouts.py (342)

File "umap/layouts.py", line 342:
def optimize_layout_generic(
    <source elided>
                dist_output, grad_dist_output = output_metric(
                    current, other, *output_metric_kwds
                    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
</details>


<details>
<summary>Code for reproducing 2:</summary>

```
import numba
import numpy as np
from umap import UMAP


@numba.njit(fastmath=True)
def euclidean_custom(x, y):
    # equivalent to existing euclidean distance function
    result = 0.0
    for i in range(x.shape[0]):
        result += (x[i] - y[i]) ** 2
    return np.sqrt(result)


np.random.seed(0)
to_reduce = np.random.uniform(0, 1, (2000, 25))
reducer = UMAP(random_state=0, metric=euclidean_custom).fit(to_reduce)
original = reducer.inverse_transform(reducer.embedding_)
```
</details>
<details>
<summary>Traceback:</summary>

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-50-eca2b67af5ee> in <module>
      13 reducer = UMAP(random_state=0, metric=euclidean_custom).fit(to_reduce)
----> 14 original = reducer.inverse_transform(reducer.embedding_)

~/Documents/Dartmouth/CDL/umap/umap/umap_.py in inverse_transform(self, X)
   2247             _input_distance_func,
   2248             tuple(self._metric_kwds.values()),
-> 2249             verbose=self.verbose,
   2250         )
   2251 

~/opt/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

~/opt/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

~/opt/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
failed to unpack float64

File "umap/layouts.py", line 506:
def optimize_layout_inverse(
    <source elided>
                dist_output, grad_dist_output = output_metric(
                    current, other, *output_metric_kwds
                    ^

[1] During: typing of exhaust iter at /Users/paxtonfitzpatrick/Documents/Dartmouth/CDL/umap/umap/layouts.py (506)

File "umap/layouts.py", line 506:
def optimize_layout_inverse(
    <source elided>
                dist_output, grad_dist_output = output_metric(
                    current, other, *output_metric_kwds
                    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
</details>

**Comment by lmcinnes** [comment]
I would be more than happy with a PR -- you seem to have already done all the legwork on digging into the problem, so I suspect you'll be faster than me getting it resolved at this point. Thaks for all your effort on this, it is definitely greatly appreciated.
