### ISSUE TITLE
EOFError by loading umap model

### ISSUE THREAD

**Issue by p-dre** [lmcinnes/umap#522]
I have created a umap model and saved it via joblib. Then I try to load the model on another PC but with the same environment. My memory is 50% full. Is it not possible to save an umap model with joblib?

```
umap_model_plot = umap.UMAP(n_neighbors=15,
                               n_components=2,
                               metric='cosine').fit(emb)

joblib.dump(umap_model_plot,'umap_2.sav')
```

Load model

```

joblib.load('umap_2.sav')
Traceback (most recent call last):

  File "<ipython-input-9-ef20fd6f570e>", line 1, in <module>
    joblib.load('umap_2.sav')

  File "C:\Users\Paul\AppData\Roaming\Python\Python37\site-packages\joblib\numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)

  File "C:\Users\Paul\AppData\Roaming\Python\Python37\site-packages\joblib\numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()

  File "C:\Users\Paul\Anaconda3\envs\top2vec_final\lib\pickle.py", line 1086, in load
    raise EOFError

EOFError
```

**Comment by dylanking42** [comment]
this is almost impossible to debug with this little information:
possible things to look at, for you:

1. if you moved the model, you could be missing actual bytes (thats my first guess by EOF error) because the move didn't work perfectly.
2. If the model got compressed during the move maybe that's bad? depending on compression algo?
3. if moving between windows and unix that could be bad
4. if there are ANY dependency mis matches between the two systems that could be bad

also, my OCD is triggered by you naming the `UMAP()` object as a `plot`. are you trying to load the `.save` as a `.png` accidentally?
