### ISSUE TITLE
Fit on array of size >= 4096 failed when using custom user defined metrics 

### ISSUE THREAD

**Issue by chingheng113** [lmcinnes/umap#556]
Hi, 
Thank you for your hard work. I'm using a custom user defined metrics for UMAP.
It works fine when sample size is small, but when its sample size is lager than 4,096, is results in the following error.
After some experiments, I didn't encounter the error as trying #547 's example.
But had similar issue as  #472 mentioned.

Reproducible example:
```
import numpy as np
import umap

def red_channel_dist(a,b):
    return np.abs(a[0] - b[0])

np.random.seed(42)
data = np.random.rand(4096, 4)

fit = umap.UMAP(metric=red_channel_dist)
u = fit.fit_transform(data)
```
Error msg:
```
Traceback (most recent call last):
  File "D:/Projects/reStroke/distython_master/tttt.py", line 12, in <module>
    u = fit.fit_transform(data)
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\umap\umap_.py", line 2635, in fit_transform
    self.fit(X, y)
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\umap\umap_.py", line 2379, in fit
    ) = nearest_neighbors(
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\umap\umap_.py", line 328, in nearest_neighbors
    knn_search_index = NNDescent(
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\pynndescent\pynndescent_.py", line 903, in __init__
    self._neighbor_graph = nn_descent(
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\numba\core\dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\numba\core\dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
During: typing of argument at C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\pynndescent\pynndescent_.py (361)

File "C:\Users\USER\anaconda3\envs\reStroke\lib\site-packages\pynndescent\pynndescent_.py", line 361:
def nn_descent(
    <source elided>

    if init_graph[0].shape[0] == 1:  # EMPTY_GRAPH
    ^

This error may have been caused by the following argument(s):
- argument 4: Cannot determine Numba type of <class 'function'>
```

**Comment by chingheng113** [comment]
The problem was fixed by compiling the custom user defined metrics in nopython mode by numba.
(as mentioned at https://umap-learn.readthedocs.io/en/latest/parameters.html#metric)
```
import numpy as np
import umap
import numba

@numba.njit()
def red_channel_dist(a,b):
    return np.abs(a[0] - b[0])

np.random.seed(42)
data = np.random.rand(4096, 4)

fit = umap.UMAP(metric=red_channel_dist)
u = fit.fit_transform(data)
```

Thanks
