### ISSUE TITLE
Unable to complete basic fit_transform() : numba.core.errors.TypingError

### ISSUE THREAD

**Issue by carsteen** [lmcinnes/umap#557]
Hello,

For the reccord, I wanted to share the error for passing floats to UMAP int arguments such as n_components. or n_neighbors. After painfull research over numba, found that input parameters type were the issue., which now seems obvious when reading the error...
Thanks for your great work

Reproducible example
```
from umap import UMAP
import numpy as np

data = np.random.rand(500, 8)

ClusterEstimator = UMAP(min_dist= 0.01, n_components= 8.0, n_neighbors= 4.0)
ClusterEstimator.fit_transform(data)
```

Error
```
Traceback (most recent call last):
  File "debug_umap2.py", line 10, in <module>
    a = ClusterEstimator.fit_transform(df)
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/umap/umap_.py", line 2635, in fit_transform
    self.fit(X, y)
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/umap/umap_.py", line 2350, in fit
    self.densmap or self.output_dens,
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/umap/umap_.py", line 558, in fuzzy_simplicial_set
    X, n_neighbors, metric, metric_kwds, angular, random_state, verbose=verbose,
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/umap/umap_.py", line 313, in nearest_neighbors
    knn_indices = fast_knn_indices(X, n_neighbors)
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function empty>) found for signature:
 
 >>> empty(Tuple(int64, float64), dtype=class(int32))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'empty': File: numba/core/typing/npydecl.py: Line 507.
    With argument(s): '(Tuple(int64, float64), dtype=class(int32))':
   No match.

During: resolving callee type: Function(<built-in function empty>)
During: typing of call at /home/raphrecovery/envs/datastack37/lib/python3.7/site-packages/umap/utils.py (30)


File "../../../../envs/datastack37/lib/python3.7/site-packages/umap/utils.py", line 30:
def fast_knn_indices(X, n_neighbors):
    <source elided>
    """
    knn_indices = np.empty((X.shape[0], n_neighbors), dtype=np.int32)
    ^
```

**Comment by lmcinnes** [comment]
Thanks for documenting this. I'm sure it will be helpful for others. I'll see if there is a way to get more sensible errors.
