### ISSUE TITLE
Numba issues while importing UMAP

### ISSUE THREAD

**Issue by MAlexandraOliveira** [lmcinnes/umap#570]
I have installed umap-learn and all its requirements, such as numba. However, when importing umap it raises an error related to numba experimentals. I am not being able to solve it.

The error is displayed in the image.
Thanks in advance
<img width="650" alt="numba" src="https://user-images.githubusercontent.com/43906345/106721154-3927b680-65fc-11eb-8c26-b6fb2871619b.PNG">

**Comment by fenaux** [comment]
After installing UMAP with condaforge,I got a similar problem :
import umap
Traceback (most recent call last):
  File "<ipython-input-86-623e299b05c0>", line 1, in <module>  import umap
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/umap/__init__.py", line 2, in <module> from .umap_ import UMAP
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/umap/umap_.py", line 32, in <module|> import umap.sparse as sparse
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/umap/sparse.py", line 12, in <module>  from umap.utils import norm
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/umap/utils.py", line 39, in <module> @numba.njit("i4(i8[:])")
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/decorators.py", line 218, in wrapper    disp.compile(sig)
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 776, in compile
    def _rebuild(cls, uuid, py_func, locals, targetoptions, impl_kind,
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "<string>", line 1, in <module>
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/types/abstract.py", line 187, in __getitem__
    return Array(dtype=self, ndim=ndim, layout=layout)
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/types/abstract.py", line 66, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "/home/fenaux/anaconda3/lib/python3.7/site-packages/numba/core/types/npytypes.py", line 411, in __init__
    super(Array, self).__init__(dtype, ndim, layout, name=name)
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by lmcinnes** [comment]
I can't say for sure, but I suspect you need a newer version of numba (0.51 or newer should do the job). I can't say why that didn't get handled by the requirements / dependencies listed for umap-learn, but it is the most likely explanation.

**Comment by fenaux** [comment]
Thank for your answer
Here are the package installed by conda-forge
llvmlite-0.34.0      | 297 KB    | ##################################### | 100% 
certifi-2020.12.5    | 143 KB    | ##################################### | 100% 
umap-learn-0.5.0     | 122 KB    | ##################################### | 100% 
ca-certificates-2020 | 137 KB    | ##################################### | 100% 
numba-0.51.2         | 3.6 MB    | ##################################### | 100% 
pynndescent-0.5.1    | 41 KB     | ##################################### | 100% 
libllvm10-10.0.1     | 26.4 MB   | ##################################### | 100% 

So numba version satisfies your recommendation.
If I try to install numba with conda numba0.52 is not installed. Probably no fit my environment.

**Comment by lmcinnes** [comment]
It looks like conda-forge is doing the right thing, so that's all fine. Admittedly the conda-forge error you posted is a little different, so perhaps we are getting closer to getting it working for you. It looks like it is having trouble compiling the norm function. I'm not sure why that should be the case -- it has been in the code that way for a long time, and this is the first time I've heard of an error like that. Regardless, it is clearly stopping things working for you. One potential approach is to remove the signature on that particular line. I.e. edit the file: /home/fenaux/anaconda3/lib/python3.7/site-packages/umap/utils.py at line 39 from:

```python
@numba.njit("i4(i8[:])")
```

to

```python
@numba.njit()
```

and see if that helps. This may be simply pushing the problem to elsewhere. You may also want to try asking the numba people if they have seen this sort of error before. I would reccommend their gitter channel, where you may be able to get a relatively swift response -- at least as to whether they've seen anything quite like this before.

**Comment by fenaux** [comment]
I got this error
ImportError: cannot import name 'tau_rand_int' from 'umap.utils' (/home/fenaux/anaconda3/lib/python3.7/site-packages/umap/utils.py)

**Comment by lmcinnes** [comment]
It seems like there is something broken with your installation generally then :-( I am really not quite sure what the best way to diagnose it is. There are some issues right now related to numpy, but it should not be affecting numba in this way. I admit that I am at a loss, and don't really have any more suggestions right now. Sorry.
