### ISSUE TITLE
import umap error

### ISSUE THREAD

**Issue by kunwang34** [lmcinnes/umap#714]
Hi there,

I'm using python==3.9.1, umap-learn==0.4.6 and numba==0.53.1
Here's errors when I'm trying to run 'import umap'.
I don't have any idea with the traceback.
Please let me know if you have any thought.

Traceback (most recent call last):
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\errors.py", line 744, in new_error_context
    yield
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import umap
  File "C:\Users\xxx\miniconda3\lib\site-packages\umap\__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "C:\Users\xxx\miniconda3\lib\site-packages\umap\umap_.py", line 54, in <module>
    from umap.layouts import (
  File "C:\Users\xxx\miniconda3\lib\site-packages\umap\layouts.py", line 39, in <module>
    def rdist(x, y):
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
    raise e
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\typed_passes.py", line 384, in run_pass
    lower.lower()
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\xxx\miniconda3\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\xxx\miniconda3\lib\site-packages\numba\core\errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
[1m[1mStoring i64 to ptr of i32 ('dim'). FE type int32
[1m
File "..\..\Users\xxx\miniconda3\lib\site-packages\umap\layouts.py", line 52:[0m
[1mdef rdist(x, y):
    <source elided>
    result = 0.0
[1m    dim = x.shape[0]
[0m    [1m^[0m[0m
[0m
[0m[1mDuring: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at C:\Users\xxx\miniconda3\lib\site-packages\umap\layouts.py (52)[0m

**Comment by lmcinnes** [comment]
I think the answer is that numba has gotten a bit stricter in recent releases. This shouldn't be too hard to fix.

**Comment by kunwang34** [comment]
@lmcinnes Thanks a lot. I upgraded the umap-learn to 0.5.1 and it works fine now.
