### ISSUE TITLE
Error when trying to load a saved UMAP object.

### ISSUE THREAD

**Issue by arcanum-henry** [lmcinnes/umap#759]
Hi there - firstly, thanks for developing this library, I've found it extremely useful.

I'm running into issues trying to load a saved UMAP object. I've run into the same problem using both pickle and joblib. I'm currently using umap=0.4.6, pynndescent=0.5.4, and numba=0.51.2, due to [this problem](https://github.com/lmcinnes/umap/issues/746).

I've been trying to load in a pickled UMAP object, and have been running into the following error:

`loaded_mapper = pickle.load(open("org_emb_estimator.sav", "rb"))`

```TypingError                               Traceback (most recent call last)
/tmp/ipykernel_8870/719780631.py in <module>
----> 1 loaded_mapper = pickle.load(open("org_emb_estimator.sav", "rb"))

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/pynndescent/pynndescent_.py in __setstate__(self, d)
   1026     def __setstate__(self, d):
   1027         self.__dict__ = d
-> 1028         self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
   1029 
   1030     def _init_search_graph(self):

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/pynndescent/pynndescent_.py in <listcomp>(.0)
   1026     def __setstate__(self, d):
   1027         self.__dict__ = d
-> 1028         self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
   1029 
   1030     def _init_search_graph(self):

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/pynndescent/rp_trees.py in renumbaify_tree(tree)
   1176     point_indices = numba.typed.List.empty_list(point_indices_type)
   1177 
-> 1178     hyperplanes.extend(tree.hyperplanes)
   1179     offsets.extend(tree.offsets)
   1180     children.extend(tree.children)

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/typedlist.py in extend(self, iterable)
    364             # can not be sliced.
    365             self._initialise_list(iterable[0])
--> 366         return _extend(self, iterable)
    367 
    368     def remove(self, item):

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function impl_extend at 0x7f129d7e9ca0>) found for signature:

 >>> impl_extend(ListType[array(float64, 2d, C)], reflected list(array(float32, 1d, C))<iv=None>)

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'impl_extend': File: numba/typed/listobject.py: Line 1027.
    With argument(s): '(ListType[array(float64, 2d, C)], reflected list(array(float32, 1d, C))<iv=None>)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   - Resolution failure for literal arguments:
   No implementation of function Function(<function impl_append at 0x7f129d7e9430>) found for signature:

    >>> impl_append(ListType[array(float64, 2d, C)], array(float32, 1d, C))

   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'impl_append': File: numba/typed/listobject.py: Line 589.
           With argument(s): '(ListType[array(float64, 2d, C)], array(float32, 1d, C))':
          Rejected as the implementation raised a specific error:
            LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
          
          
          File "../../../.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/listobject.py", line 597:
              def impl(l, item):
                  casteditem = _cast(item, itemty)
                  ^
          
          During: lowering "$8call_function.3 = call $2load_global.0(item, $6load_deref.2, func=$2load_global.0, args=[Var(item, listobject.py:597), Var($6load_deref.2, listobject.py:597)], kws=(), vararg=None)" at /home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/listobject.py (597)
     raised from /home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/utils.py:81
   
   - Resolution failure for non-literal arguments:
   None
   
   During: resolving callee type: BoundFunction((<class 'numba.core.types.containers.ListType'>, 'append') for ListType[array(float64, 2d, C)])
   During: typing of call at /home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/listobject.py (1051)
   
   
   File "../../../.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/listobject.py", line 1051:
               def impl(l, iterable):
                   <source elided>
                   for i in iterable:
                       l.append(i)
                       ^

  raised from /home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/typeinfer.py:1071

- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.containers.ListType'>, 'extend') for ListType[array(float64, 2d, C)])
During: typing of call at /home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/typedlist.py (101)


File "../../../.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/typed/typedlist.py", line 101:
def _extend(l, iterable):
    return l.extend(iterable)
    ^```

Would greatly appreciate any help resolving this :)

**Comment by arcanum-henry** [comment]
**Update:** I've tried this again with:

- umap=0.5.1
- pynndescent=0.5.4 (same as before)
- numba=0.51.2 (same as before)

I can successfully save and load UMAP objects trained on a small amount of data, signalling that the above error may have been resolved in the newer version of umap. However, for any reasonably sized data (in my case 4330 rows), I run into the following error when trying to save UMAP objects:

```
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 487, in save
    data_name = overloads[key]
KeyError: ((array(int64, 2d, C), array(float32, 2d, C), array(float32, 2d, C), type(CPUDispatcher(<function alternative_hellinger at 0x7fb596143700>)), array(int64, 1d, C), float64), ('x86_64-unknown-linux-gnu', 'skylake-avx512', '+64bit,+adx,+aes,+avx,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,-avx512er,+avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vpopcntdq,+bmi,+bmi2,-cldemote,+clflushopt,+clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,+pku,+popcnt,-prefetchwt1,+prfchw,-ptwrite,-rdpid,+rdrnd,+rdseed,-rtm,+sahf,-sgx,-sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-xop,+xsave,+xsavec,+xsaveopt,+xsaves'), ('8f4e945651d82115cfc3db905c3166c775bacc37ce80f97fb200c896ef6e6bd4', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/dev/ff-code-classification-rnd/ff_code_classification/scripts/make_org_embeddings.py", line 115, in <module>
    if __name__ == "__main__":
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ec2-user/dev/ff-code-classification-rnd/ff_code_classification/scripts/make_org_embeddings.py", line 110, in pipeline
    joblib.dump(emb_mapper, "org_emb_estimator.sav")
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 480, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 485, in dump
    self.save(obj)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 282, in save
    return Pickler.save(self, obj)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 282, in save
    return Pickler.save(self, obj)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 282, in save
    return Pickler.save(self, obj)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/pickle.py", line 576, in save
    rv = reduce(self.proto)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 902, in __getstate__
    self._init_search_graph()
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 995, in _init_search_graph
    diversified_rows, diversified_data = diversify(
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/dispatcher.py", line 434, in _compile_for_args
    raise e
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/dispatcher.py", line 367, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/dispatcher.py", line 825, in compile
    self._cache.save_overload(sig, cres)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 671, in save_overload
    self._save_overload(sig, data)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 681, in _save_overload
    self._cache_file.save(key, data)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 496, in save
    self._save_index(overloads)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 542, in _save_index
    data = self._dump(data)
  File "/home/ec2-user/.pyenv/versions/3.8.5/envs/safe/lib/python3.8/site-packages/numba/core/caching.py", line 570, in _dump
    return pickle.dumps(obj, protocol=-1)
TypeError: cannot pickle 'weakref' object
```

**Comment by lmcinnes** [comment]
Worst case, try downgrading to an earlier pynndescent version (0.5.1 should work). I'm still trying to figure out the right way to deal with all of this.
