### ISSUE TITLE
Error in transform()

### ISSUE THREAD

**Issue by dawe** [lmcinnes/umap#81]
I was trying to apply `UMAP.transform()` to embed new data on a fitted UMAP instance. Unfortunately I get an error:

```
TypingError                               Traceback (most recent call last)
<ipython-input-75-c35306a6db40> in <module>()
----> 1 XY = U.transform(nx.adj_matrix(nx.subgraph(huG, E)).toarray())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/umap/umap_.py in transform(self, X)
   1566                 self._random_init,
   1567                 self._tree_init,
-> 1568                 rng_state,
   1569             )
   1570             result = self._search(

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/umap/nndescent.py in initialise_search(forest, data, query_points, n_neighbors, init_from_random, init_from_tree, rng_state)
    159 ):
    160     results = make_heap(query_points.shape[0], n_neighbors)
--> 161     init_from_random(n_neighbors, data, query_points, results, rng_state)
    162     if forest is not None:
    163         for tree in forest:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345         except errors.UnsupportedError as e:
    346             # Something unsupported is present in the user code, add help info

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x11916b470>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/errors.py", line 491, in new_error_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/typeinfer.py", line 194, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/typeinfer.py", line 138, in propagate
    constraint(typeinfer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/typeinfer.py", line 195, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/errors.py", line 499, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba-0.38.1-py3.6-macosx-10.6-intel.egg/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: 
[1] During: typing of argument at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/umap/nndescent.py (125)
--%<----------------------------------------------------------------------------


File "../../../../../../Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/umap/nndescent.py", line 125:
    def init_from_random(n_neighbors, data, query_points, heap, rng_state):
        for i in range(query_points.shape[0]):
        ^

This error may have been caused by the following argument(s):
- argument 1: cannot determine Numba type of <class 'scipy.sparse.csr.csr_matrix'>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by lmcinnes** [comment]
The condensed version of that long and complicated traceback is that UMAP's
transform doesn't current accept sparse matrices as input. Obviously I
should have had better input validation on that. There s nothing in
principle that would stop sparse matrix input from working, but I will need
to go through the code and find the places that need to be fixed or
rewritten to make it go through. Hopefully a future release will close the
gap for you. In the meantime, presuming you have a sufficiently small case
you can try casting to dense.

**Comment by dawe** [comment]
Training data were sparse but fitting went fine. Test data were dense. I will try with dense training data, then.

**Comment by lmcinnes** [comment]
Ah, that's not as good. I'll definitely have to look into this a little
further and make sparse handling more robust in general. Sorry for the
issues.
