### ISSUE TITLE
module 'umap' has no attribute 'UMAP'

### ISSUE THREAD

**Issue by renzha-miun** [lmcinnes/umap#828]
I tried to run the example code published at https://www.kaggle.com/jack89roberts/the-journey-of-an-image-through-a-neural-network/notebook, but I got a error: "module 'umap' has no attribute 'UMAP'"

Here is the information. 

Input...Traceback (most recent call last):
  File "/Users/renzha/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/visualization of cnn.py", line 484, in <module>
    nvis.umap_layers(range(251))
  File "/Users/renzha/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/visualization of cnn.py", line 244, in umap_layers
    pipe_out = umap.UMAP ().fit_transform (pipe_in)
AttributeError: module 'umap' has no attribute 'UMAP'

How to solve the problem? Thank you.

**Comment by renzha-miun** [comment]
just found out that ```umap-learn``` need to be installed.

**Comment by ranabanik** [comment]
I had `umap 0.1.1` installed. But had the same error. Then installed 'umap-learn 0.5.2`. Still got the error and then uninstalled `umap`. 
It worked. 
>> from umap import UMAP

**Comment by agombert** [comment]
from this [answer](https://stackoverflow.com/questions/57242208/how-to-resolve-the-error-module-umap-has-no-attribute-umap-i-tried-installi)

```bash
pip uninstall umap
pip install umap-learn
```

```python
import umap.umap_ as umap
```

**Comment by vaaale** [comment]
This worked for me:

from umap.umap_ import UMAP

**Comment by diracdyson** [comment]
This is resolved someone with authority take this down

**Comment by chandrasekarnarayana** [comment]
`pip install umap-learn` is still giving error `pip install umap-learn==0.5.2` worked for me.

**Comment by jayant-yadav** [comment]
@lmcinnes please apply a patch so that beginners like me can at least start using this awesome library.

**Comment by Terrence-zzh** [comment]
> `pip install umap-learn` is still giving error `pip install umap-learn==0.5.2` worked for me.

my python version is 3.7, and only the method works for me. Thanks for you.

**Comment by mattolson93** [comment]
If you are a fool like me and named your experiment `umap.py` that will cause this issue as well.

**Comment by 201power** [comment]
same issue here with fiftyone compute_visulization(), install umap-learn==0.5.2 did not solve the issue.
