### ISSUE TITLE
ufunc 'sparse_correct_alternative_hellinger' did not contain a loop with signature matching types <class 'numpy.dtype[float32]'> -> None

### ISSUE THREAD

**Issue by uninstallit** [lmcinnes/umap#871]
Not sure if I am doing something wrong but I am consistently getting the error above 4000 rows when using `UMAP`. I do not understand the error message - I would really appreciate some help. 

Here is the important part of the code:
```
    tfidf_vectorizer = TfidfVectorizer(min_df=5, stop_words="english")
    tfidf_word_doc_matrix = tfidf_vectorizer.fit_transform(
        notam_df["text_column"].tolist()
    )
    tfidf_embedding = umap.UMAP(metric="hellinger", n_neighbors=15).fit(
        tfidf_word_doc_matrix
    )
```

and here is the traceback:
```
Traceback (most recent call last):
  File "C:\Users\Edvin\Desktop\first-model\DAEN690\src\models\umap_model.py", line 66, in <module>
    main()
  File "C:\Users\Edvin\Desktop\first-model\DAEN690\src\models\umap_model.py", line 57, in main
    tfidf_embedding = umap.UMAP(metric="hellinger", n_neighbors=5).fit(
  File "C:\Users\Edvin\AppData\Roaming\Python\Python310\site-packages\umap\umap_.py", line 2516, in fit
    ) = nearest_neighbors(
  File "C:\Users\Edvin\AppData\Roaming\Python\Python310\site-packages\umap\umap_.py", line 342, in nearest_neighbors
    knn_indices, knn_dists = knn_search_index.neighbor_graph
  File "C:\Users\Edvin\AppData\Roaming\Python\Python310\site-packages\pynndescent\pynndescent_.py", line 1564, in neighbor_graph
    self._distance_correction(self._neighbor_graph[1]),
numpy.core._exceptions._UFuncNoLoopError: ufunc 'sparse_correct_alternative_hellinger' did not contain a loop with signature matching types <class 'numpy.dtype[float32]'> -> None
```

**Comment by uninstallit** [comment]
More info: I ran this on Windows 10 - but then I shared my code with a friend on a mac - and ran no problem with 50k.

**Comment by uninstallit** [comment]
Upgraded numpy to latest (`numpy 1.22.4`) and fixed it.
