### ISSUE TITLE
Error in training encoder decoder in Parametric UMAP with 1D vector data.

### ISSUE THREAD

**Issue by evancresswell** [lmcinnes/umap#923]
Hello,

I am trying to fit transform data with Parametric UMAP using Keras architecture for the encoder and decoder as described in docs. The data is of the shape (74096,1) and I have 100 samples for testing. I want to embed to 2D. My architecture is as follows 

## Setup
```
    dims = (74096,1)
    latent_dim = 2
```

## Encoder
```
    encoder_inputs = keras.Input(shape=dims)
    xe = layers.Conv1D(32, 3, activation="relu", strides=2, padding="same",name='conv1')(encoder_inputs)
    xe = layers.Conv1D(64, 3, activation="relu", strides=2, padding="same",name='conv2')(xe)
    xe = layers.Flatten(name='flatten')(xe)
    xe = layers.Dense(16, activation="relu")(xe)
    z_mean = layers.Dense(latent_dim, name="z_mean")(xe)
    z_log_var = layers.Dense(latent_dim, name="z_log_var")(xe)
    z = Sampling()([z_mean, z_log_var])
    encoder = keras.Model(encoder_inputs, [z_mean, z_log_var, z], name="encoder")


 Layer (type)                   Output Shape         Param #     Connected to                     
==================================================================================================
 input_94 (InputLayer)          [(None, 74093, 1)]   0           []                               
                                                                                                  
 conv1 (Conv1D)                 (None, 37047, 32)    128         ['input_94[0][0]']               
                                                                                                  
 conv2 (Conv1D)                 (None, 18524, 64)    6208        ['conv1[0][0]']                  
                                                                                                  
 flatten (Flatten)              (None, 1185536)      0           ['conv2[0][0]']                  
                                                                                                  
 dense_139 (Dense)              (None, 16)           18968592    ['flatten[0][0]']                
                                                                                                  
 z_mean (Dense)                 (None, 2)            34          ['dense_139[0][0]']              
                                                                                                  
 z_log_var (Dense)              (None, 2)            34          ['dense_139[0][0]']              
                                                                                                  
 sampling_37 (Sampling)         (None, 2)            0           ['z_mean[0][0]',                 
                                                                  'z_log_var[0][0]']   
```
## Decoder

```
# This simply gets the mirror of the encoder set up
reshape_dims = (encoder.get_layer('conv2').output_shape[1], encoder.get_layer('conv2').output_shape[2])


latent_inputs = keras.Input(shape=(latent_dim))
xd = layers.Dense(16 , activation="relu")(latent_inputs)
xd = layers.Dense(encoder.get_layer('flatten').output_shape[1], activation="relu")(xd)
xd = layers.Reshape(reshape_dims)(xd)
xd = layers.Conv1DTranspose(64, 3, activation="relu", strides=2, padding="same")(xd)
xd = layers.Conv1DTranspose(32, 3, activation="relu", strides=2, padding="same")(xd)
decoder_outputs = layers.Conv1DTranspose(1, 3, activation="sigmoid", padding="same")(xd)
decoder = keras.Model(latent_inputs, decoder_outputs, name="decoder")

Model: "decoder"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_95 (InputLayer)       [(None, 2)]               0         
                                                                 
 dense_140 (Dense)           (None, 16)                48        
                                                                 
 dense_141 (Dense)           (None, 1185536)           20154112  
                                                                 
 reshape_55 (Reshape)        (None, 18524, 64)         0         
                                                                 
 conv1d_transpose_118 (Conv1  (None, 37048, 64)        12352     
 DTranspose)                                                     
                                                                 
 conv1d_transpose_119 (Conv1  (None, 74096, 32)        6176      
 DTranspose)                                                     
                                                                 
 conv1d_transpose_120 (Conv1  (None, 74096, 1)         97        
 DTranspose)                                                     
                                                                 
=================================================================
Total params: 20,172,785
Trainable params: 20,172,785
Non-trainable params: 0
```

With this defined I set up my Parametric UMAP to fit to data called alignment_onehot (shape: (100, 74093)) using validation data val_onehot (shape: (10, 74093)).

```
    embedder = ParametricUMAP(
        encoder=encoder,
         decoder=decoder,
        dims=dims,
        parametric_reconstruction= True,
         reconstruction_validation=val_onehot,
        verbose=True,
        random_state=42
    )
embedding = embedder.fit_transform(alignment_onehot)
```
but when I try to fit the data I get the following Errors:
### Input 0 of layer "decoder" is incompatible with the layer: expected shape=(None, 2), found shape=(3, 100, 2)
I'm not sure where the shape 3 comes from?? There are 100 embedded data points with latent dimension 2 but I'm confused on where how the 3 is included.. 

Here is the full output/error:
## Output
```
ParametricUMAP(decoder=<keras.engine.functional.Functional object at 0x2aaedfb64520>, dims=(74093, 1), encoder=<keras.engine.functional.Functional object at 0x2ab0f50a6190>, optimizer=<keras.optimizers.optimizer_v2.adam.Adam object at 0x2ab101f80070>, parametric_reconstruction=True, reconstruction_validation=array([[1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.]]))
Wed Oct  5 13:14:13 2022 Construct fuzzy simplicial set
Wed Oct  5 13:14:14 2022 Finding Nearest Neighbors
Wed Oct  5 13:14:14 2022 Finished Nearest Neighbor Search
Wed Oct  5 13:14:14 2022 Construct embedding
WARNING:tensorflow:Model was constructed with shape (None, 2) for input KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name='input_95'), name='input_95', description="created by layer 'input_95'"), but it was called on an input with incompatible shape (3, None, 2).
Epoch 1/10
```
## Error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_119266/1148489687.py in <module>
      5 
      6 
----> 7 embedding = embedder.fit_transform(alignment_onehot)

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/parametric_umap.py in fit_transform(self, X, y, precomputed_distances)
    215             return super().fit_transform(precomputed_distances, y)
    216         else:
--> 217             return super().fit_transform(X, y)
    218 
    219     def transform(self, X):

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/umap_.py in fit_transform(self, X, y)
   2770             Local radii of data points in the embedding (log-transformed).
   2771         """
-> 2772         self.fit(X, y)
   2773         if self.transform_mode == "embedding":
   2774             if self.output_dens:

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/parametric_umap.py in fit(self, X, y, precomputed_distances)
    200             return super().fit(precomputed_distances, y)
    201         else:
--> 202             return super().fit(X, y)
    203 
    204     def fit_transform(self, X, y=None, precomputed_distances=None):

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/umap_.py in fit(self, X, y)
   2682 
   2683         if self.transform_mode == "embedding":
-> 2684             self.embedding_, aux_data = self._fit_embed_data(
   2685                 self._raw_data[index],
   2686                 self.n_epochs,

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/parametric_umap.py in _fit_embed_data(self, X, n_epochs, init, random_state)
    460 
    461         # create embedding
--> 462         history = self.parametric_model.fit(
    463             edge_dataset,
    464             epochs=self.loss_report_frequency * self.n_training_epochs,

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/engine/training.py in tf__train_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/parametric_umap.py in train_step(self, data)
   1133 
   1134         with tf.GradientTape() as tape:
-> 1135             y_pred = self(x, training=True)  # Forward pass
   1136             # Compute the loss value
   1137             # (the loss function is configured in `compile()`)

ValueError: in user code:

    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/engine/training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/engine/training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/umap/parametric_umap.py", line 1135, in train_step
        y_pred = self(x, training=True)  # Forward pass
    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/data/cresswellclayec/conda/envs/DCA_ER/lib/python3.9/site-packages/keras/engine/input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "gradient_clipped_model_8" "                 f"(type GradientClippedModel).
    
    Input 0 of layer "decoder" is incompatible with the layer: expected shape=(None, 2), found shape=(3, 100, 2)
    
    Call arguments received by layer "gradient_clipped_model_8" "                 f"(type GradientClippedModel):
      • inputs=('tf.Tensor(shape=(100, 74093, 1), dtype=float32)', 'tf.Tensor(shape=(100, 74093, 1), dtype=float32)')
      • training=True
      • mask=None

```

**Comment by evancresswell** [comment]
I should say that I believe, maybe naively, that this is happening because Parametric umap is expecting 2D data (ie image data, (28, 28,1) ) and not the 1D data I'm using.. and that the embedded data is being re-cast weirdly inside umap before it is submitted to the decoder (hence the transition from the output (None, 2) --> (3, None, 2) )..

**Comment by timsainb** [comment]
Hi Evan,

Can you try using the default encoder and decoder, rather than the convolutional networks?

**Comment by evancresswell** [comment]
Hello Tim,

Thanks for your quick response! It works with the default encoder and decoder.

However the resulting embedding isn't very good. I was hoping a convolutional network would solve the issue given the nature of the sequence data. For illustration here is an example embedding with the 100 sample data points (I ran the same analysis for 10000 data points with little difference in embedded grouping).

![image](https://user-images.githubusercontent.com/10620771/194194925-ac9ee3db-c026-4a4f-8f6b-36feaaf5a0f2.png)

**Comment by timsainb** [comment]
You could try an rnn encoder and decoder. You also will probably see more structure if you crop the outliers in your plot.

**Comment by timsainb** [comment]
I’m going to mark this as closed since the original error is resolved but feel free to respond.

**Comment by timsainb** [comment]
Looking through the network you defined, it looks like you took that architecture from a vae?

**Comment by evancresswell** [comment]
I did use vae as inspiration given that it has been effective in analyzing this type of data before (genome sequence data) and it seemed a natural fit with umap.

Just for my own understanding though: is the error I was having on the umap end? Is it just simply that parametric umap was not meant to handle 1D data? The example from the website used 2D convolutions. 
```
WARNING:tensorflow:Model was constructed with shape (None, 2) for input KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (3, None, 2).
```
Given the error it just seems that umap is passing something weird into the decoder.. I assumed that as long as my networks took the correct input shape and gave the correct output shape I should be fine regardless of the internals..

>  You also will probably see more structure if you crop the outliers in your plot.

Also those outliers persevere, when more data is included, very strange. I really want to get this architecture to work but I will try an rnn for the encoder and decoder. Thanks!

**Comment by timsainb** [comment]
Hey, no, the issue is not on the UMAP end. If you can write an auto encoder in tensorflow with your dataset you should be able to use the same encoder here
