### ISSUE TITLE
installing [plot] yield assertion error

### ISSUE THREAD

**Issue by gg4u** [lmcinnes/umap#981]
I spot this error using:

!pip install umap-learn[plot]

I don't know yet if critical, I am learning how to use the package:

<img width="798" alt="Screenshot 2023-03-05 at 10 25 51 AM" src="https://user-images.githubusercontent.com/284214/222952540-9c283f49-66e5-4dfb-8cb1-3c21852a60d3.png">

Full trace:

```
Requirement already satisfied: umap-learn[plot] in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (0.5.3)
Requirement already satisfied: scikit-learn>=0.22 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (1.2.1)
Requirement already satisfied: numba>=0.49 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (0.56.4)
Requirement already satisfied: scipy>=1.0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (1.10.1)
Requirement already satisfied: pynndescent>=0.5 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (0.5.8)
Requirement already satisfied: numpy>=1.17 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (1.23.5)
Requirement already satisfied: tqdm in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (4.64.1)
Requirement already satisfied: seaborn in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (0.12.2)
Collecting scikit-image
  Using cached scikit_image-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.2 MB)
Requirement already satisfied: matplotlib in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (3.7.0)
Collecting bokeh
  Using cached bokeh-3.0.3-py3-none-any.whl (16.5 MB)
Requirement already satisfied: pandas in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from umap-learn[plot]) (1.5.3)
Collecting colorcet
  Using cached colorcet-3.0.1-py2.py3-none-any.whl (1.7 MB)
Collecting holoviews
  Using cached holoviews-1.15.4-py2.py3-none-any.whl (4.3 MB)
Collecting datashader
  Using cached datashader-0.14.4-py2.py3-none-any.whl (18.2 MB)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from numba>=0.49->umap-learn[plot]) (0.39.1)
Requirement already satisfied: setuptools in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from numba>=0.49->umap-learn[plot]) (59.6.0)
Requirement already satisfied: joblib>=0.11 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from pynndescent>=0.5->umap-learn[plot]) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from scikit-learn>=0.22->umap-learn[plot]) (3.1.0)
Requirement already satisfied: tornado>=5.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (6.2)
Requirement already satisfied: contourpy>=1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (1.0.7)
Requirement already satisfied: PyYAML>=3.10 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (6.0)
Collecting xyzservices>=2021.09.1
  Using cached xyzservices-2023.2.0-py3-none-any.whl (55 kB)
Requirement already satisfied: pillow>=7.1.0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (9.4.0)
Requirement already satisfied: packaging>=16.8 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (23.0)
Requirement already satisfied: Jinja2>=2.9 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bokeh->umap-learn[plot]) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from pandas->umap-learn[plot]) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from pandas->umap-learn[plot]) (2.8.2)
Collecting pyct>=0.4.4
  Using cached pyct-0.5.0-py2.py3-none-any.whl (15 kB)
Collecting param
  Using cached param-1.12.3-py2.py3-none-any.whl (87 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting xarray
  Using cached xarray-2023.2.0-py3-none-any.whl (975 kB)
Requirement already satisfied: requests in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from datashader->umap-learn[plot]) (2.28.2)
Collecting datashape
  Using cached datashape-0.5.2-py3-none-any.whl
Collecting dask
  Using cached dask-2023.3.0-py3-none-any.whl (1.2 MB)
Collecting pyviz-comms>=0.7.4
  Using cached pyviz_comms-2.2.1-py2.py3-none-any.whl (42 kB)
Collecting panel>=0.13.1
  Using cached panel-0.14.4-py2.py3-none-any.whl (20.8 MB)
Requirement already satisfied: kiwisolver>=1.0.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from matplotlib->umap-learn[plot]) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from matplotlib->umap-learn[plot]) (4.38.0)
Requirement already satisfied: pyparsing>=2.3.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from matplotlib->umap-learn[plot]) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from matplotlib->umap-learn[plot]) (0.11.0)
Collecting imageio>=2.4.1
  Using cached imageio-2.26.0-py3-none-any.whl (3.4 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.8 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2023.2.28-py3-none-any.whl (216 kB)
Collecting networkx>=2.8
  Using cached networkx-3.0-py3-none-any.whl (2.0 MB)
Requirement already satisfied: lazy_loader>=0.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from scikit-image->umap-learn[plot]) (0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from Jinja2>=2.9->bokeh->umap-learn[plot]) (2.1.2)
Requirement already satisfied: markdown in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from panel>=0.13.1->holoviews->umap-learn[plot]) (3.4.1)
Requirement already satisfied: bleach in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from panel>=0.13.1->holoviews->umap-learn[plot]) (6.0.0)
Requirement already satisfied: typing-extensions in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from panel>=0.13.1->holoviews->umap-learn[plot]) (4.5.0)
Collecting bokeh
  Using cached bokeh-2.4.3-py3-none-any.whl (18.5 MB)
Requirement already satisfied: six>=1.5 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->umap-learn[plot]) (1.16.0)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting partd>=1.2.0
  Using cached partd-1.3.0-py3-none-any.whl (18 kB)
Requirement already satisfied: cloudpickle>=1.1.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from dask->datashader->umap-learn[plot]) (2.2.1)
Collecting fsspec>=0.6.0
  Using cached fsspec-2023.3.0-py3-none-any.whl (145 kB)
Collecting multipledispatch>=0.4.7
  Using cached multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Requirement already satisfied: idna<4,>=2.5 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from requests->datashader->umap-learn[plot]) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from requests->datashader->umap-learn[plot]) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from requests->datashader->umap-learn[plot]) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from requests->datashader->umap-learn[plot]) (3.0.1)
Collecting locket
  Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Requirement already satisfied: webencodings in /data0/home/h21/luas6629/venv/lib/python3.10/site-packages (from bleach->panel>=0.13.1->holoviews->umap-learn[plot]) (0.5.1)
ERROR: Exception:
Traceback (most recent call last):
  File "/data0/home/h21/luas6629/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/data0/home/h21/luas6629/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/data0/home/h21/luas6629/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/data0/home/h21/luas6629/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/data0/home/h21/luas6629/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError

```

**Comment by gg4u** [comment]
I found a solution!

Just install the dependencies for plotting, one by one in this order, it worked for me:
```
pip install datashader scikit-image
pip install bokeh 
pip install holoviews 
```

Note: holoviews uninstalled and re-installed bokeh, so error above might be due to holoviews.
